-- Provision the marketing-media storage bucket used for admin-composed social posts.
-- Private bucket: reads happen through signed URLs generated by server actions.
-- Size limit matches the spec: image ≤10MB, video ≤50MB. Cap at 50 MB total.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'marketing-media',
  'marketing-media',
  false,
  52428800, -- 50 MB
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'video/mp4',
    'video/quicktime'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
